### ISSUE TITLE
Update "Can't retrieve a list of commands" error message

### ISSUE THREAD

**Issue by BSVogler** [RedisGrafana/grafana-redis-app#100]
## Summary
For a data source, we get the error message on the Redis application overview page.
I suspect that some permission is missing. What is missing to make this work?

## Relevant information
We also have a datasource without the Multilayer security but it also shows this error message, but without the lock symbol.

<img width="387" alt="Bildschirmfoto 2022-01-03 um 10 03 42" src="https://user-images.githubusercontent.com/801818/147913905-6fb846b6-980f-4570-92af-3f557ec1ac7e.png">

**Comment by mikhailredis** [comment]
@BSVogler, Command "command" is required to retrieve the list of commands. Is it available for the user?

**Comment by BSVogler** [comment]
No, it is unfortunately not. My suggestion would be here to make that a little bit more transparent by adding that to the error message?

**Comment by mikhailredis** [comment]
@BSVogler Thank you for the feedback, I will update the code and documentation to make it clear.
Was it resolved for you and you can see your Redis instances?
