### ISSUE TITLE
Redis Latency Panel error when switching to Graph mode

### ISSUE THREAD

**Issue by nail-sirazitdinov** [RedisGrafana/grafana-redis-app#48]
### Describe the bug
Redis Latency Panel error when switching to Graph mode.
Table mode works fine.

### Version
Redis Application 1.1.0
Redis Datasource 1.3.1
Grafana v7.2.1 (72a6c64532)

### Steps to reproduce
1. Add Redis Latency Panel, choose $redis datasource
2. Table mode shows commandstats output + calculated latency as expected
3. When switching to Graph mode there is the error - `Cannot read property 'Fixed' or undefined`

### Screenshots
![image](https://user-images.githubusercontent.com/49917620/110159432-b2135d00-7db8-11eb-8217-30fd5deaf26c.png)

**Comment by mikhailredis** [comment]
@nail-sirazitdinov Thank you for reporting the issue. Color Modes were introduced after Grafana 7.2.1.
The issue is fixed in the upcoming release 1.2.0 or nightly Docker build: https://github.com/orgs/RedisGrafana/packages/container/package/redis-app

**Comment by nail-sirazitdinov** [comment]
thanks a lot for a quick fix @mikhailredis
