### ISSUE TITLE
Rebuild using 8.3.4

### ISSUE THREAD

**Issue by mikhailredis** [RedisGrafana/grafana-redis-app#99]
```
Due to an issue where Grafana would crash when loading a plugin built using a Grafana Toolkit version from 8.3.0 to 8.3.3, we've decided to deprecate these versions. As a result, the latest tag has been set to the latest working version, 8.2.7.
If your plugin was built using one of these versions, you'll need to rebuild the plugin using 8.2.7 or 8.3.4 (when it's released).

For more information, check out the announcement post:
https://community.grafana.com/t/deprecating-grafana-toolkit-versions-from-8-3-0-to-8-3-3/58325
```

**Comment by BSVogler** [comment]
Does that mean upgrading to grafana 8.3 currently breaks the redis plugin?

**Comment by mikhailredis** [comment]
@BSVogler, it's applicable only for the main branch which is based on 8.3.0. The main branch is working perfectly on the latest release 8.3.3, as I understand there is an issue with 8.2.X. In any case, because of the 0-day issue, everybody should run 8.3.
All plugins in the Grafana Marketplace should work as expected.
